### PR TITLE
added support for --outfile parameter to msgconvert script

### PR DESCRIPTION
**Pull request by meebey**

### CODE REVIEW

**Comment by mvz** [comment]
Hi @meebey, thanks for your pull request. What do you think should happen if more than one `.msg` file is given on the command line? AFAICS, it will overwrite the outfile for each message, leaving only the last one in the file.

**Comment by meebey** [comment]
Yeah I noticed that issue, but had no easy fix as argv contain a list of files to convert. The --outfile parameter is mutally exclusive with argv.count > 1. A Check and 2nd usage line in --hellp could express that. Want me to add that?

**Comment by mvz** [comment]
Yes, please.

**Comment by meebey** [comment]
Done.

**Comment by mvz** [comment]
Looks good, thanks!

**Comment by meebey** [comment]
Thank you for making this library/tool.

**Pull request merged**
