### PR TITLE
header_str_set

### PR DESCRIPTION
**Pull request by uhuntu**
Hi there, when I checking in Email::MIME::Header

=head1 DESCRIPTION

This object behaves like a standard Email::Simple header, with the following
changes:

=for :list
* the C<header> method automatically decodes encoded headers if possible
* the C<header_as_obj> method returns an object representation of the header value
* the C<header_raw> method returns the raw header; (read only for now)
* stringification uses C<header_raw> rather than C<header>

Note that C<header_set> does not do encoding for you, and expects an
encoded header.  Thus, C<header_set> round-trips with C<header_raw>,
not C<header>!  Be sure to properly encode your headers with
C<Encode::encode('MIME-Header', $value)> before passing them to
C<header_set>.  And be sure to use minimal version 2.83 of Encode
module due to L<bugs in MIME-Header|Encode::MIME::Header/BUGS>.

Alternately, if you have Unicode (character) strings to set in headers, use the
C<header_str_set> method.

=cut

### CODE REVIEW

**Comment by mvz** [comment]
Hi @uhuntu, can you explain to me what problem this change solves?

**Comment by uhuntu** [comment]
Hi @mvz I have a msg file that includes Chinese characters if I used header_set it will come out wrong characters, but if I used header_str_set it will come out right.

**Comment by ojwb** [comment]
With @uhuntu's example file which they sent me by private email (is it OK to make that public?) and the `outlookmsg2html` script from xapian-omega I see these warning messages on stderr:

```
Value for 'Subject' header with wide characters at /usr/share/perl5/Email/Outlook/Message.pm line 320.
Value for 'From' header with wide characters at /usr/share/perl5/Email/Outlook/Message.pm line 320.
Value for 'To' header with wide characters at /usr/share/perl5/Email/Outlook/Message.pm line 320.
Value for 'Cc' header with wide characters at /usr/share/perl5/Email/Outlook/Message.pm line 320.
```

That line 320 is the one this patch changes, and the proposed change eliminates these messages.  However I get identical output before and after applying the fix (and the Chinese characters in the headers seem valid in both cases).

The patch here does seem to introduce a new message though:

```
Argument contains empty host portion of address at /usr/share/perl5/Email/MIME/Encode.pm line 71.
```

Line 71 is the first of these:

```
  return $object->as_mime_string({
    charset => $charset,
    header_name_length => $header_name_length,
  });
```

**Comment by uhuntu** [comment]
Hi @ojwb , sorry I can not reproduce your seeing,

```
Value for 'Subject' header with wide characters at /usr/share/perl5/Email/Outlook/Message.pm line 320.
Value for 'From' header with wide characters at /usr/share/perl5/Email/Outlook/Message.pm line 320.
Value for 'To' header with wide characters at /usr/share/perl5/Email/Outlook/Message.pm line 320.
Value for 'Cc' header with wide characters at /usr/share/perl5/Email/Outlook/Message.pm line 320.
```

Can you tell me how you produce these lines ?

**Comment by ojwb** [comment]
I didn't do anything special - just `./outlookmsg2html chinese-example.msg` (where that's the attachment you sent me earlier) gave those warnings.

I'm testing on Debian unstable, which has these versions of the two modules:

```
ii  libemail-mime-perl            1.953-1      all          module for simple MIME message parsing
ii  libemail-outlook-message-perl 0.921-1      all          module for reading Outlook .msg files
```

**Comment by uhuntu** [comment]
@ojwb I use most recent both projects, but I still can not reproduce you issue. However, seems I submit wrong in this project, I was understanding wrong in utf8 procedure, thank you for the clarifying.

**Comment by ojwb** [comment]
I think there is something amiss with the module too.  I can reproduce the warnings above using current git master and the `msgconvert` script in it:

```
$ perl -Ilib script/msgconvert chinese-example.msg
Value for 'Subject' header with wide characters at lib/Email/Outlook/Message.pm line 331.
Value for 'From' header with wide characters at lib/Email/Outlook/Message.pm line 331.
Value for 'To' header with wide characters at lib/Email/Outlook/Message.pm line 331.
Value for 'Cc' header with wide characters at lib/Email/Outlook/Message.pm line 331.
```

Changing that line to use `header_str_set` again fixes these warnings, but again introduces:

```
Argument contains empty host portion of address at /usr/share/perl5/Email/MIME/Encode.pm line 71.
```

It seems that error comes from XS code in Email::Address::XS:

https://sources.debian.org/src/libemail-address-xs-perl/1.05-1/Email-Address-XS.xs/?hl=427#L427

This doesn't make much sense to me as all the email addresses in the message do have a host portion.

@uhuntu Is it OK to share the example file you sent me?  I have been able to reproduce the initial warning with another example file I have which has some emoji in the Email subject, but I definitely can't redistribute that one (also that one doesn't trigger the new warning after the change).

**Comment by uhuntu** [comment]
@ojwb that is okay to share the email I sent you.

**Pull request closed without merging**
